-- ============================================================
-- Migrasi: Observability / Request Metrics
-- Menambahkan tabel request_metrics untuk mencatat timing,
-- token, cost, error, dan kualitas retrieval per request chat.
-- Tidak mengubah tabel yang sudah ada (chat_logs tetap dipakai
-- sebagaimana adanya).
-- ============================================================

CREATE TABLE IF NOT EXISTS request_metrics (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id              UUID NOT NULL DEFAULT gen_random_uuid(),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Identitas request
    session_id              TEXT,
    mahasiswa_id             TEXT,
    channel                 TEXT NOT NULL DEFAULT 'unknown',   -- 'website' | 'telegram'

    -- Status akhir
    status                  TEXT NOT NULL DEFAULT 'success',   -- 'success' | 'error' | 'quota_rejected'
    error_type              TEXT,                              -- nama class exception Python
    error_source            TEXT,                              -- 'openai' | 'supabase' | 'validation' | 'rate_limit' | 'unknown'
    http_status              INT,

    -- A2: timing per tahap pipeline (dalam milidetik)
    stage_validation_ms      NUMERIC,
    stage_session_load_ms    NUMERIC,
    stage_reformulation_ms   NUMERIC,   -- tahap tambahan (query rewrite), nullable, 0 kalau tidak triggered
    stage_embedding_ms       NUMERIC,
    stage_retrieval_ms       NUMERIC,
    stage_reranking_ms       NUMERIC,
    stage_parent_assembly_ms NUMERIC,
    stage_generation_ms      NUMERIC,
    stage_db_save_ms         NUMERIC,
    total_ms                 NUMERIC,

    -- C: kualitas retrieval
    num_docs_retrieved       INT,       -- hasil hybrid search sebelum rerank
    num_docs_after_rerank    INT,       -- hasil akhir setelah threshold
    top_cross_encoder_score  NUMERIC,
    avg_cross_encoder_score  NUMERIC,
    domain_detected          TEXT,      -- 'PI' | 'KKP' | 'SKRIPSI' | 'NON_SKRIPSI' | 'UNKNOWN'
    is_no_relevant_doc       BOOLEAN NOT NULL DEFAULT FALSE,
    retrieved_parent_ids     TEXT[],    -- daftar parent_id yang dipakai jadi context akhir
    rewrite_method           TEXT,      -- 'None' | 'Rule' | 'LLM' (lihat reformulator.py)

    -- D: token & cost
    input_tokens             INT,
    output_tokens             INT,
    embedding_tokens          INT,       -- estimasi (lihat catatan Fase 4)
    llm_cost_usd              NUMERIC(12, 6),
    embedding_cost_usd        NUMERIC(12, 6),

    -- B: reliability
    openai_retry_count        INT NOT NULL DEFAULT 0,

    -- G1-G6 (Fase 10): investigasi/drill-down — ditambahkan setelah iterasi
    -- mockup UI kedua. `question` dan `username` WAJIB diisi di AWAL request
    -- (sebelum try/except di ai_services.chat(), lihat Fase 10.2), BUKAN
    -- diambil dari tabel chat_logs — karena chat_logs cuma tertulis saat
    -- request SUKSES, sedangkan kita butuh data ini juga untuk request yang
    -- ERROR (lihat requirement G3).
    question                  TEXT,      -- teks pertanyaan asli
    username                  TEXT,      -- nama tampilan (bukan ID) — dari JWT (website) atau profil Telegram
    retrieval_detail           JSONB     -- SEMUA kandidat dokumen yang sempat direranking beserta skornya,
                                          -- bukan cuma top/avg. Bentuk: [{"parent_id":"...","title":"...",
                                          -- "score":0.82,"accepted":true}, ...] — lihat Fase 10.3
);

-- Index untuk pola query agregasi (dashboard, view)
CREATE INDEX IF NOT EXISTS idx_request_metrics_created_at   ON request_metrics (created_at);
CREATE INDEX IF NOT EXISTS idx_request_metrics_session_id   ON request_metrics (session_id);
CREATE INDEX IF NOT EXISTS idx_request_metrics_channel      ON request_metrics (channel);
CREATE INDEX IF NOT EXISTS idx_request_metrics_status       ON request_metrics (status);
CREATE INDEX IF NOT EXISTS idx_request_metrics_domain       ON request_metrics (domain_detected);
CREATE INDEX IF NOT EXISTS idx_request_metrics_mahasiswa_id ON request_metrics (mahasiswa_id);
-- G4/G6: mempercepat query "list pertanyaan per domain" & "list pertanyaan no-relevant-doc"
CREATE INDEX IF NOT EXISTS idx_request_metrics_domain_no_doc ON request_metrics (domain_detected, is_no_relevant_doc);

-- Row Level Security: ikuti pola tabel lain di project ini —
-- hanya service_role (backend) yang boleh baca/tulis.
ALTER TABLE request_metrics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access on request_metrics"
    ON request_metrics
    FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');